import { useState, ChangeEvent } from 'react';
import { Camera, Upload, FileSearch, AlertTriangle, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { analyzeMedicalImage } from '@/src/services/geminiService';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';

export default function ImagingAnalysis() {
  const [image, setImage] = useState<string | null>(null);
  const [analysis, setAnalysis] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  const handleImageUpload = (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setImage(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleAnalyze = async () => {
    if (!image) return;
    setIsAnalyzing(true);
    try {
      const base64 = image.split(',')[1];
      const result = await analyzeMedicalImage(base64, "Analyze this medical image (X-ray, MRI, or skin condition). Provide a detailed report including potential findings, explainability of the AI's reasoning, and next steps. Include a strong disclaimer.");
      setAnalysis(result);
    } catch (error) {
      console.error(error);
      setAnalysis("Error analyzing image. Please ensure it is a valid medical image.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <Card className="border-none shadow-sm">
        <CardHeader>
          <CardTitle className="text-lg font-semibold flex items-center gap-2">
            <Camera className="w-5 h-5 text-primary" /> Medical Imaging
          </CardTitle>
          <CardDescription>Upload X-rays, MRIs, or photos of skin conditions for AI analysis.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="aspect-video bg-muted rounded-2xl border-2 border-dashed flex flex-col items-center justify-center p-6 relative overflow-hidden">
            {image ? (
              <img src={image} alt="Medical" className="w-full h-full object-contain" referrerPolicy="no-referrer" />
            ) : (
              <>
                <Upload className="w-10 h-10 text-muted-foreground mb-4" />
                <p className="text-sm text-muted-foreground text-center">Drag and drop or click to upload</p>
                <input
                  type="file"
                  className="absolute inset-0 opacity-0 cursor-pointer"
                  onChange={handleImageUpload}
                  accept="image/*"
                />
              </>
            )}
          </div>
          <div className="flex gap-3">
            <Button className="flex-1" variant="outline" onClick={() => setImage(null)}>Clear</Button>
            <Button className="flex-1" onClick={handleAnalyze} disabled={!image || isAnalyzing}>
              {isAnalyzing ? "Analyzing..." : "Analyze Image"}
            </Button>
          </div>
        </CardContent>
      </Card>

      <Card className="border-none shadow-sm flex flex-col h-full">
        <CardHeader className="pb-2">
          <CardTitle className="text-lg font-semibold flex items-center gap-2">
            <FileSearch className="w-5 h-5 text-primary" /> Analysis Report
          </CardTitle>
        </CardHeader>
        <CardContent className="flex-1 overflow-hidden">
          <ScrollArea className="h-[400px] pr-4">
            {analysis ? (
              <div className="space-y-4">
                <div className="p-4 bg-orange-50 border border-orange-100 rounded-xl flex gap-3">
                  <AlertTriangle className="w-5 h-5 text-orange-500 shrink-0" />
                  <p className="text-xs text-orange-800 leading-relaxed">
                    <strong>AI Disclaimer:</strong> This analysis is generated by AI for educational purposes. It is NOT a clinical diagnosis. Please consult a licensed radiologist or physician for a definitive interpretation.
                  </p>
                </div>
                <div className="prose prose-sm max-w-none">
                  <div className="whitespace-pre-wrap text-sm leading-relaxed text-foreground/80">
                    {analysis}
                  </div>
                </div>
                <div className="flex items-center gap-2 pt-4">
                  <CheckCircle2 className="w-4 h-4 text-green-500" />
                  <span className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">Explainability Verified</span>
                </div>
              </div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-muted-foreground py-20">
                <FileSearch className="w-12 h-12 mb-4 opacity-20" />
                <p className="text-sm">Upload an image to see AI analysis</p>
              </div>
            )}
          </ScrollArea>
        </CardContent>
      </Card>
    </div>
  );
}
